Sprint3 iteration 12
Jeskay/musthave_metrics pull request #5
Opened 2024-11-08 16:06 UTC by Jeskay

1. Agent is now sending metrics in batch if the server supports new API
2.  Server accepts updating metrics in batches via JSON API
3.  Random number is now generated with the respect to postgres restrictions to double precision type

2024-11-09 10:57 UTC, Perederey reviewed
Привет! Из критичного нужно возвращать ошибки в функциях, а не panic и использовать типизированные параметры.
В остальном код написан хорошо!

2024-11-09 10:57 UTC, Perederey commented on internal/metric/db/postgres.go
> +	_, err := ps.db.Exec(`
Тут можно кстати, использовать константы для SQL запросов, вынеси их в отдельные переменные на уровне пакета

2024-11-09 10:57 UTC, Perederey commented on internal/metric/service.go
Вынеси бизнес-логику обработки метрик в отдельный пакет domain, оставив в service (это application cлой) только координацию между слоями

2024-11-09 10:57 UTC, Perederey commented on config/config.go
>  	Address      string `env:"ADDRESS"`
а где REPORT_INTERVAL и POLL_INTERVAL для агента, которые требовались до этогоо заданию? Добавь их в структуру ServerConfig

2024-11-09 10:57 UTC, Perederey commented on internal/metric/db/memory.go
> +func (ms *MemStorage) GetMany(keys []string) []*internal.Metric {
В методе GetMany используй make с указанием ожидаемой емкости для улучшения производительности, по факту это `len(keys)`

2024-11-09 10:57 UTC, Perederey commented on internal/metric/db/postgres.go
> +func (ps *PostgresStorage) Set(key string, value internal.MetricValue) {
Использование panic в методах хранилища может привести к падению приложения. Лучше возвращать ошибки, это прям musthave.

```go
func (ps *PostgresStorage) Set(key string, value internal.MetricValue) error {
    if value.Type == internal.CounterMetric {
        _, err := ps.db.Exec(`
            INSERT INTO metric (name, countervalue)
            VALUES ($1, $2)
            ON CONFLICT (name) DO UPDATE
                SET countervalue = excluded.countervalue;
        `, key, value.Value)
        return err
    }
    _, err := ps.db.Exec(`
        INSERT INTO metric (name, gaugevalue)
        VALUES ($1, $2)
        ON CONFLICT (name) DO UPDATE
            SET gaugevalue = excluded.gaugevalue;
    `, key, value.Value)
    return err
}

2024-11-09 10:57 UTC, Perederey commented on internal/metric/db/postgres.go
> +func (ps *PostgresStorage) SetMany(values []internal.Metric) {
Тут не надо использовать queryBuilder, а нужно использовать типизированные параметры

2024-11-12 04:43 UTC, Jeskay commented on config/config.go
>  	Address      string `env:"ADDRESS"`
Они нужны только для агента, поэтому лежат в AgentConfig. Не понял зачем они серверу

2024-11-12 04:45 UTC, Jeskay commented on internal/metric/db/postgres.go
> +func (ps *PostgresStorage) Set(key string, value internal.MetricValue) {
Я думал добавить recover на уровне выше, потому что запросы могут падать сразу с паникой без ошибки.

2024-11-12 04:46 UTC, Jeskay commented on internal/metric/db/postgres.go
> +func (ps *PostgresStorage) SetMany(values []internal.Metric) {
Не совсем понял, что такое типизированные параметры. Имеется ввиду интерфейсы Valuer и Scanner?

2024-11-12 07:55 UTC, Jeskay commented on internal/metric/service.go
Я не совсем понял как её там обернуть. Кажется что только таймер на сохранение можно явно вынести из сервиса.

2024-11-12 07:55 UTC, Jeskay commented on internal/metric/db/memory.go
> +func (ms *MemStorage) GetMany(keys []string) []*internal.Metric {
Исправил

2024-11-13 22:58 UTC, bulbetski requested changes
Код хороший, в основном замечания по потенциально опасным местам вызывающим панику -- разыменования указателей и примедения типов без проверки

2024-11-13 22:58 UTC, bulbetski commented on internal/Dto/metric.go
> +			*v.Delta = *v.Delta + *value.Delta
Перед разыменованием указателей стоит проверять значения Delta на nil, чтобы избежать паники.
Как вариант можно сделать геттеры и сеттеры

2024-11-13 22:58 UTC, bulbetski commented on internal/agent/request/json.go
> +			metric = dto.NewGaugeMetrics(m.Name, m.Value.Value.(float64))
если `m.Value.Value` содержит не int64 или float64, приведение типа приведет к панике.
нужно проверить через type assertion `if t,ok := x.(T); !ok { //ошибка }`

2024-11-13 22:58 UTC, bulbetski commented on internal/agent/service.go
> +}
хорошей практикой было бы возвращать ошибку в случае err != nil и StatusCode != http.StatusOK.

Так же можно было бы вынести эти проверки в main, чтобы падать с fatal ошибкой.
Таким образом мы не будем перегружать код нашего пакета service доп полями и проверками

2024-11-13 22:58 UTC, bulbetski commented on internal/agent/service.go
> +				continue
можно добавить логирование для упрощения отладки

2024-11-13 22:58 UTC, bulbetski commented on internal/metric/db/memory.go
> +		return m.(internal.MetricValue), ok
Приведение `m.(internal.MetricValue)` может вызвать панику, если тип не совпадает

2024-11-13 22:58 UTC, bulbetski commented on internal/metric/db/memory.go
> +			return nil, fmt.Errorf("key %s does not exists", key)
Ошибка при отсутствии ключа завершит функцию. Альтернативно, можно пропускать отсутствующие ключи и собирать только существующие.

2024-11-13 22:58 UTC, bulbetski commented on internal/metric/db/memory.go
> +		m = append(m, &internal.Metric{Name: key.(string), Value: value.(internal.MetricValue)})
Приведение типа `value.(internal.MetricValue)` без проверки может вызвать панику

2024-11-13 22:58 UTC, bulbetski commented on internal/metric/db/postgres.go
> +	}
коннект лучше сделать в мэйне и фаталится, если у нас не получится подключится к бд. А если решишь оставить здесь, то надо возаращать ошибку

2024-11-13 22:58 UTC, bulbetski commented on internal/metric/db/postgres.go
> +		return &PostgresStorage{db: nil}
надо возвращать ошибку

2024-11-13 22:58 UTC, bulbetski commented on internal/metric/db/postgres.go
> +		return internal.MetricValue{}, false
лучше возвращать как ошибки, ну или хотя бы сами ошибки логировать

2024-11-13 22:58 UTC, bulbetski commented on internal/metric/service.go
> +			s.storage.Set(m.Name, m.Value)
Подскажи, а почему Set не возвращает ошибки, в чем задумка?

2024-11-13 22:58 UTC, bulbetski commented on internal/repository.go
> +		m.Value.Value = *metric.Value
разыменование указателей, надо проверять на nil

2024-11-14 12:39 UTC, Jeskay commented on internal/agent/service.go
> +}
Согласен со всем кроме полного выноса проверки в main. Так как необходимо чтобы сервис имел обратную совместимость, то эта проверка лишь на доступность API в формате json из последних инкрементов. В тестах до 9 этот route не существует, хотя сам сервер работает, так что приходится делать вот так)

2024-11-14 13:42 UTC, bulbetski approved these changes

2024-11-14 13:44 UTC, bulbetski commented on cmd/agent/main.go
> -		os.Exit(1)
ну тут просто не os.Exit() нужен, а фатал какой-нибудь

2024-11-14 14:44 UTC, merged