Iter15
Jeskay/musthave_metrics pull request #8
Opened 2024-11-18 18:48 UTC by Jeskay

1. Added rate limiting for agent service
2. Added secondary metrics in agent service
3. Implemented hash sum check on both server and agent

2024-11-20 22:50 UTC, bulbetski requested changes
Код хороший, прикопался в основном по мелочам. Единственное, что прямо стоит исправление -- вынесение воркер пула в отдельный пакет

2024-11-20 22:50 UTC, bulbetski commented on internal/agent/metrics.go
> +var metricSecondaryList = []string{
Ну если докапываться прям, то можно назвать как-то более информативно

2024-11-20 22:50 UTC, bulbetski commented on internal/agent/request/json.go
> +	WriteHash(req, buf.Bytes(), hashKey)
Не обрабатываем ошибку

2024-11-20 22:50 UTC, bulbetski commented on internal/agent/request/json.go
> +	WriteHash(req, buf.Bytes(), hashKey)
Не обрабатываем ошибку

2024-11-20 22:50 UTC, bulbetski commented on internal/agent/request/json.go
>  	req, err = http.NewRequest(http.MethodPost, url, &buf)
и тут не обрабатываем

2024-11-20 22:50 UTC, bulbetski commented on internal/agent/request/json.go
>  	req, err = http.NewRequest(http.MethodPost, url, &buf)
и тут не обрабатываем

2024-11-20 22:50 UTC, bulbetski commented on internal/agent/service.go
> +		svc.storage.Set(dto.NewGaugeMetrics("CPUutilization1", float64(v.Used)))
Не обрабатываются ошибки. И выше тоже не обрабатываются. 
Надо как-то хитро еще обернуть, потому что 50 раз одно и то же дублируется 

svc.storage.Set(dto.NewCounterMetrics ......

2024-11-20 22:50 UTC, bulbetski commented on internal/agent/service.go
> +			r, err := request.MetricsPostJson(svc.config.HashKey, batch, url)
подвинь обработку ошибки прям под err

2024-11-20 22:50 UTC, bulbetski commented on internal/agent/service.go
> +}
Логика воркер пула встроена в сервис, это не оч хорошо. Стоит вынести во отдельную библиотеку

Че-то такое будет
```
type WorkerPool[T any] struct {
    workerCount int
}

func New(workerCount int) *WorkerPool[T] {
    return &WorkerPool[T]{workerCount: workerCount}
}

func (wp *WorkerPool[T]) Run(jobs <-chan T, handler func(T)) { // имплементация }
```

2024-11-20 22:50 UTC, bulbetski commented on internal/agent/service.go
> +			res, err = http.DefaultClient.Do(req)
Использование глобального http.DefaultClient делает код менее тестируемым и зависимым от внешних настроек. Стоит сделать http.Client зависимостью AgentService

2024-11-20 22:50 UTC, bulbetski commented on internal/agent/service.go
> +		res.Body.Close()
Body стоит закрывать в defer'e

2024-11-20 22:50 UTC, bulbetski commented on internal/metric/middleware/hash_decoder.go
> +		hash := ctx.GetHeader("HashSHA256")
можно вынести эту строку в константу

2024-11-20 22:50 UTC, bulbetski commented on internal/metric/middleware/hash_decoder.go
> +				ctx.AbortWithStatus(http.StatusBadRequest)
Можно использовать AbortWithStatusJSON, чтобы вернуть сообщение об ошибке

2024-11-20 22:50 UTC, bulbetski commented on internal/metric/middleware/hash_decoder.go
> +		hash := ctx.GetHeader("HashSHA256")
так же стоит проверять наличие hash и падать в случае его отсутствия

2024-11-20 22:50 UTC, bulbetski commented on internal/metric/middleware/hash_decoder.go
> +			}
после каждого AbortWithStatusJSON или AbortWithStatus добавить явный return

2024-11-22 18:15 UTC, Jeskay commented on internal/agent/service.go
> +		svc.storage.Set(dto.NewGaugeMetrics("CPUutilization1", float64(v.Used)))
Ничего элегантнее, чем использовать уже существующий метод SetMany я не придумал)

2024-11-22 18:18 UTC, Jeskay commented on internal/agent/service.go
> +}
Мне кстати интересно, как в go принято реализовывать перегрузки функций? Потому что с воркер пулом может понадобиться реализация с возвращаемыми значениями и с перегрузкой бы прям красиво это можно было сделать, не делая вторую структуру с другим дженериком.

2024-11-25 09:27 UTC, bulbetski approved these changes

2024-11-25 09:27 UTC, bulbetski commented on internal/agent/request/json.go
> +		return
не блокер, но напиши значения в return. 

p.s. вкусовщина, но я бы не использовал именованные return'ы вооьще

2024-11-25 09:27 UTC, bulbetski commented on internal/agent/request/json.go
> +		return
то же самое

2024-11-25 09:27 UTC, bulbetski commented on internal/agent/service.go
> +	err := svc.storage.SetMany([]dto.Metrics{
намного лучше, чем было

2024-11-25 09:27 UTC, bulbetski commented on internal/agent/service.go
> +}
в моей голове прям принципиальных отличий нет. воркер пул можно вполне универсальный написать с использованием дженериков. Как правило он на вход принимает какой-то json payload, где описаны поля, необходимые для выполнения джобы -- тип и непосредственно структура какая-то специфичная для таски. Благодаря типу мы можем успешно размаршалить структуру для таски и запустить правильный обработчик.

Ну это если говорить прям об универсальности какой-то. В целом какого-нибудь дженерика, который принимает на вход функцию и возвращает ошибку зачастую достаточно.

2024-11-25 09:27 UTC, bulbetski commented on internal/metric/middleware/hash_decoder.go
> +				ctx.AbortWithStatus(http.StatusBadRequest)
базар

2025-04-17 13:04 UTC, merged